services:
  db_mysql:
    container_name: db_mysql
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - database
    volumes:
      - mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  db_phpmyadmin:
    container_name: db_phpmyadmin
    depends_on:
      - db_mysql
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - database
    environment:
      - PMA_HOST=db_mysql
      - PMA_PORT=${MYSQL_PORT}
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}

networks:
  database:
    driver: bridge

volumes:
  mysql:
